//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int cId { get; set; }
        public string comment { get; set; }
        public System.DateTime date { get; set; }
        public int qid { get; set; }
        public string uid { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Writers Writers { get; set; }
    }
}
